# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

minecraft_version=1.21.9
supported_versions=
yarn_mappings=1.21.9+build.1
enabled_platforms=fabric,neoforge

# Mod Properties
mod_version = 2.1.2
maven_group = net.puzzlemc
archives_base_name = puzzle
release_type=release
curseforge_id=563977
modrinth_id=3IuO68q1

# Modloaders
fabric_loader_version=0.17.2
fabric_api_version=0.133.14+1.21.9

neoforge_version=21.9.3-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Libraries
midnightlib_version = 1.8.1+1.21.9
modmenu_version = 15.0.0-beta.1

# Mod Integrations
cull_leaves_version = 3.0.2-fabric
ldl_version = 4.0.0+1.21.4
lbg_version = 1.5.2+1.20.1
iris_version = 1.8.0-beta.3+1.21-fabric
continuity_version = 3.0.0-beta.5+1.21
animatica_version = 0.6.1+1.21
colormatic_version = 3.1.2
borderless_mining_version = 1.1.8+1.20.1
dynamic_fps_version = 3.6.3
toml4j_version = 0.7.2
cit_resewn_version = 1.1.3+1.20
complete_config_version = 2.3.0
spruceui_version=5.0.0+1.20
emf_version=2.4.1
etf_version=6.2.10
exordium_version=1.2.1-1.20.2
# Required for LBG
quilt_loader_version=0.19.0-beta.18
quilt_fabric_api_version=7.0.1+0.83.0-1.20
