modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "Puzzle"
logoFile = "puzzle.png"
authors = "PuzzleMC, Motschen"
description = '''
Unlocks advanced capabilities for resourcepack authors, such as customizing the splashscreen and allowing for bigger block models.
'''

[[mixins]]
config = "puzzle-models.mixins.json"
[[mixins]]
config = "puzzle-predicates.mixins.json"
[[mixins]]
config = "puzzle-splashscreen.mixins.json"
[[mixins]]
config = "puzzle-splashscreen_neoforge.mixins.json"

[[dependencies.puzzle]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.puzzle]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"